# Site settings
title: OasisCom - Documentacion
email: info@oasiscom.com
description: >
  La mejor forma de conocer y usar OasisCom.
baseurl: ""
url: "http://docs.oasiscom.com"
logo: OasisCom_logot.png
twitter_username: oasiscom
github_username:  oasiscom
plugins:
  - jekyll-seo-tag
google_analytics: UA-58678143-8

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
markdown: kramdown
theme: jekyll-theme-slate
repository: OasisCom/Docs
